sudo: required
services:

language: node_js
node_js:
  - "10"

before_install:
  - npm i -g npm@6.4.1 

before_script:
  - npm install -g @angular/cli@7.1.4

script:
  - npm install
  - ng build --prod
